/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_webpki_sks_testclib_AESProvider */

#ifndef _Included_org_webpki_sks_testclib_AESProvider
#define _Included_org_webpki_sks_testclib_AESProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_webpki_sks_testclib_AESProvider
 * Method:    createAESProvider
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_webpki_sks_testclib_AESProvider_createAESProvider
  (JNIEnv *, jobject);

/*
 * Class:     org_webpki_sks_testclib_AESProvider
 * Method:    deleteAESProvider
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_webpki_sks_testclib_AESProvider_deleteAESProvider
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_webpki_sks_testclib_AESProvider
 * Method:    setKey
 * Signature: (J[BZ)V
 */
JNIEXPORT void JNICALL Java_org_webpki_sks_testclib_AESProvider_setKey
  (JNIEnv *, jobject, jlong, jbyteArray, jboolean);

/*
 * Class:     org_webpki_sks_testclib_AESProvider
 * Method:    encrypt
 * Signature: (J[B[BZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_webpki_sks_testclib_AESProvider_encrypt
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
